Reuse symbol table in partest compilation
With this change and the previous commit that reused the ambient
JVM for test execution, I have the majority of `partest --run`
successful.

```
⚡ pbpaste | grep -v ok
Selected 1876 tests drawn from 1 named test categories

% scalac run/Course-2002-01.scala
!!  215 - run/junitForwarders                       [compilation failed]
!!  799 - run/t1430                                 [compilation failed]
!! 1273 - run/t5938.scala                           [non-zero exit code]
!! 1464 - run/t6989                                 [compilation failed]
!! 1572 - run/t7817-tree-gen.scala                  [non-zero exit code]
!! 1586 - run/t7936                                 [compilation failed]
!! 1587 - run/t7936b                                [compilation failed]
!! 1598 - run/t8046                                 [non-zero exit code]
[error] Uncaught exception when running partest: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Error running /Users/jz/code/scala/test/files/run/bcodeInlinerMixed
[trace] Stack trace suppressed: run last test/it:testOnly for the full output.
[error] Error: Total 1, Failed 0, Errors 1, Passed 0
[error] Error during tests:
[error] 	partest
[error] (test/it:testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 828 s, completed 26/02/2018 8:25:02 PM
>
```

This is running on my branch:

https://github.com/retronym/scala/tree/topic/jptest

The performance is great: only using a single worker in partest
(which is about 1.5x CPU when you account for JIT and GC), we're
down to 14minutes.